repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace  # Remove espaços em branco no final de linha
    -   id: end-of-file-fixer  # Garante que os arquivos terminem com uma nova linha
    -   id: check-yaml  # Verifica se os arquivos YAML estão bem formados
    -   id: check-json  # Verifica se os arquivos JSON estão bem formados

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5.7'  # Use a versão desejada
    hooks:
    -   id: autopep8 # Formata o código Python
        args: ['--aggressive', '--aggressive', '--in-place']  # Argumentos para autopep8

# -   repo: https://gitlab.com/pycqa/flake8
#     rev: 3.8.4  # Escolha uma versão específica para evitar surpresas
#     hooks:
#     -   id: flake8
#         args: ['--max-line-length=88']  # limite de comprimento de linha, padrão é 79
#         exclude: ^build/  # Pasta para excluir da verificação

# -   repo: https://github.com/psf/black
#     rev: 21.8b0  # Use a versão mais recente
#     hooks:
#     -   id: black
#         args: ['--line-length=88']  # Estilo de formatação de código, compatível com flake8 acima

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.782  # Use a versão mais recente
#     hooks:
#     -   id: mypy
#         args: ['--ignore-missing-imports']  # Ignora imports que o mypy não pode resolver

# -   repo: https://github.com/pre-commit/pygrep-hooks
#     rev: v1.8.0  # Use a versão mais recente
#     hooks:
#     -   id: python-check-blanket-noqa
#         args: ['--per-file-ignores=*.kv:Q000']  # Ignora certas regras para arquivos Kivy (.kv)
